https: true
certs:
  web:
    create: false
config:
  issuer: https://dex.dex:32000
  web:
    tlsCert: /etc/dex/tls/https/server/tls.crt
    tlsKey: /etc/dex/tls/https/server/tls.key
  # Instead of reading from an external storage, use this list of clients.
  staticClients:
  - id: kubeapps
    redirectURIs:
    - 'http://localhost:3000/oauth2/callback'
    name: 'Kubeapps'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  staticPasswords:
  # Both users have a bcrypt hash of the string "password"
  - email: "kubeapps-operator@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  - email: "kubeapps-user@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "kubeapps-user"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5467"
  connectors:
  - type: ldap
    name: OpenLDAP
    id: ldap
    config:
      host: ldap-openldap.ldap:389

      # No TLS for this setup.
      insecureNoSSL: true

      # This would normally be a read-only user.
      bindDN: cn=admin,dc=example,dc=org
      bindPW: password

      usernamePrompt: Email Address

      userSearch:
        baseDN: ou=People,dc=example,dc=org
        filter: "(objectClass=person)"
        username: mail
        # "DN" (case sensitive) is a special attribute name. It indicates that
        # this value should be taken from the entity's DN not an attribute on
        # the entity.
        idAttr: DN
        emailAttr: mail
        nameAttr: cn

      groupSearch:
        baseDN: ou=Groups,dc=example,dc=org
        filter: "(objectClass=groupOfNames)"

        # A user is a member of a group when their DN matches
        # the value of a "member" attribute on the group entity.
        userAttr: DN
        groupAttr: member

        # The group name should be the "cn" value.
        nameAttr: cn
grpc: false
