frontend:
  replicaCount: 1
  service:
    type: NodePort
    nodePort: 30000
assetsvc:
  replicaCount: 1
dashboard:
  replicaCount: 1
kubeops:
  replicaCount: 1
postgresql:
  replication:
    enabled: false
  existingSecret: postgresql-db
kubeappsapis:
  replicaCount: 1
ingress:
  enabled: true
  hostname: localhost
  tls: true
  extraTls:
  - hosts:
    - localhost
    secretName: localhost-tls
