https: true
certs:
  web:
    create: false
config:
  issuer: https://dex.dex:32000
  web:
    tlsCert: /etc/dex/tls/https/server/tls.crt
    tlsKey: /etc/dex/tls/https/server/tls.key
  # Instead of reading from an external storage, use this list of clients.
  staticClients:
  - id: kubeapps
    redirectURIs:
    - 'http://localhost:3000/oauth2/callback'
    name: 'Kubeapps'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  staticPasswords:
  # Both users have a bcrypt hash of the string "password"
  - email: "kubeapps-operator@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  - email: "kubeapps-user@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "kubeapps-user"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5467"
grpc: false
