# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"

# Hardcode some packages to the revisions locked in client-go 5.0.1
# See https://github.com/kubernetes/client-go/blob/master/INSTALL.md#dep-not-supported-yet
[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "019ae5ada31de202164b118aee88ee2d14075c31"

[[constraint]]
  name = "k8s.io/api"
  revision = "6c6dac0277229b9e9578c5ca3f74a4345d35cdc2"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.9.1"

[prune]
  go-tests = true
  unused-packages = true
