# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.32.0"

[[constraint]]
  branch = "master"
  name = "github.com/gosuri/uitable"

[[constraint]]
  name = "github.com/rakyll/statik"
  version = "0.1.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/rakyll/statik"
    unused-packages = false
