{{- if .Values.useHelm3 -}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kubeapps.kubeops.fullname" . }}
  labels:
    app: {{ template "kubeapps.kubeops.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ template "kubeapps.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - "kubeapps.com"
    resources:
      - apprepositories
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kubeapps.kubeops.fullname" . }}
  labels:
    app: {{ template "kubeapps.kubeops.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ template "kubeapps.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kubeapps.kubeops.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kubeapps.kubeops.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.allowNamespaceDiscovery }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kubeapps:controller:kubeops-ns-discovery-{{ .Release.Namespace }}"
  labels:
    app: {{ template "kubeapps.kubeops.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ template "kubeapps.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kubeapps:controller:kubeops-ns-discovery-{{ .Release.Namespace }}"
  labels:
    app: {{ template "kubeapps.kubeops.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ template "kubeapps.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kubeapps:controller:kubeops-ns-discovery-{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "kubeapps.kubeops.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- if .Values.featureFlags.operators }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kubeapps:controller:kubeops-operators-{{ .Release.Namespace }}"
  labels:
    app: {{ template "kubeapps.kubeops.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ template "kubeapps.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups:
      - packages.operators.coreos.com
    resources:
      - packagemanifests/icon
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kubeapps:controller:kubeops-operators-{{ .Release.Namespace }}"
  labels:
    app: {{ template "kubeapps.kubeops.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ template "kubeapps.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kubeapps:controller:kubeops-operators-{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "kubeapps.kubeops.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
{{- end }}{{/* matches useHelm3 */}}
