apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubeapps.fullname" . }}
  labels:
    app: {{ template "kubeapps.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kubeapps.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kubeapps-frontend-config.yaml") . | sha256sum }}
      labels:
        app: {{ template "kubeapps.fullname" . }}
        release: {{ .Release.Name }}
    spec:
{{- include "kubeapps.imagePullSecrets" . | indent 6 }}
      containers:
      - name: nginx
        image: {{ template "kubeapps.image" (list .Values.frontend.image .Values.global) }}
        livenessProbe:
{{ toYaml .Values.frontend.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.frontend.readinessProbe | indent 10 }}
        volumeMounts:
        - name: vhost
          mountPath: /opt/bitnami/nginx/conf/server_blocks
        ports:
        - name: http
          containerPort: 8080
        resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
    {{- if .Values.authProxy.enabled }}
      - name: auth-proxy
        args:
        - -provider={{ required "You must fill \".Values.authProxy.provider\" with the provider. Valid values at https://pusher.github.io/oauth2_proxy/auth-configuration" .Values.authProxy.provider }}
        - -client-id={{ required "You must fill \".Values.authProxy.clientID\" with the Client ID of the provider" .Values.authProxy.clientID }}
        - -client-secret={{ required "You must fill \".Values.authProxy.clientSecret\" with the Client Secret of the provider" .Values.authProxy.clientSecret }}
        - -cookie-secret={{ required "You must fill \".Values.authProxy.cookieSecret\" with a 16, 24 or 32 byte base64 encoded seed string for secure cookies" .Values.authProxy.cookieSecret }}
        - -upstream=http://localhost:8080/
        - -http-address=0.0.0.0:3000
        - -email-domain={{ .Values.authProxy.emailDomain }}
        - -pass-basic-auth=false
        - -pass-access-token=true
        - -pass-authorization-header=true
        {{- range .Values.authProxy.additionalFlags }}
        - {{ . }}
        {{- end }}
        image: {{ template "kubeapps.image" (list .Values.authProxy.image .Values.global) }}
        ports:
        - name: proxy
          containerPort: 3000
        resources:
{{ toYaml .Values.authProxy.resources | indent 12 }}
    {{- end }}
      volumes:
      - name: vhost
        configMap:
          name: {{ template "kubeapps.frontend-config.fullname" . }}
    {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
    {{- with .Values.frontend.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.frontend.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
