{{- if .Values.useHelm3 -}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "kubeapps.kubeops.fullname" . }}
  labels:
    app: {{ template "kubeapps.kubeops.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - "kubeapps.com"
    resources:
      - apprepositories
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "kubeapps.kubeops.fullname" . }}
  labels:
    app: {{ template "kubeapps.kubeops.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kubeapps.kubeops.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kubeapps.kubeops.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end }}{{/* matches useHelm3 */}}
