{{- if not .Values.useHelm3 -}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - "kubeapps.com"
    resources:
      - apprepositories
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kubeapps.tiller-proxy.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.allowNamespaceDiscovery }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}-ns-discovery
  labels:
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}-ns-discovery
  labels:
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}-ns-discovery
subjects:
  - kind: ServiceAccount
    name: {{ template "kubeapps.tiller-proxy.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
{{- end }}{{/* matches useHelm3 */}}
