{{- if not .Values.useHelm3 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:
    app: {{ template "kubeapps.name" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ template "kubeapps.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tillerProxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
    release: {{ .Release.Name }}
{{- end }}{{/* matches useHelm3 */}}
