{{- if not .Values.useHelm3 -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ template "kubeapps.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}{{/* matches useHelm3 */}}
