apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kubeapps.tiller-proxy.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kubeapps.tiller-proxy.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: proxy
        image: "{{ .Values.tillerProxy.image.repository }}:{{ .Values.tillerProxy.image.tag }}"
        command:
        - /proxy
        args:
        - --host={{ .Values.tillerProxy.host }}
        ports:
        - name: http
          containerPort: {{ .Values.chartsvc.service.port }}
        resources:
{{ toYaml .Values.tillerProxy.resources | indent 12 }}
    {{- with .Values.tillerProxy.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tillerProxy.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tillerProxy.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
