{{-  if .Values.tillerProxy.tls -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ca.crt: |-
{{ .Values.tillerProxy.tls.ca | b64enc | indent 4 }}
  tls.crt: |-
{{ .Values.tillerProxy.tls.cert | b64enc | indent 4 }}
  tls.key: |-
{{ .Values.tillerProxy.tls.key | b64enc | indent 4 }}
{{- end -}}
