# Preset Roles and ClusterRoles that can be bound to users for use with Kubeapps
# See https://github.com/kubeapps/kubeapps/blob/master/docs/user/access-control.md

{{- define "kubeapps.user-rbac.labels" -}}
  labels:
    app: {{ template "kubeapps.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}

{{- if .Values.rbac.create -}}
# kubeapps-applications-read
# Gives read-only access to all the elements within a Namespace.
# Usage:
#   Apply kubeapps-applications-read clusterrole to user/serviceaccount in the desired namespace
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubeapps-applications-read
{{ template "kubeapps.user-rbac.labels" . }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch
---
# kubeapps-service-catalog-read
# Gives read-only access to Service Instances and Bindings within a Namespace in Kubeapps.
# Usage:
#   Apply kubeapps-service-catalog-read clusterrole to user/serviceaccount in the desired namespace
#   AND apply kubeapps-service-catalog-browse to user/serviceaccount in all namespaces.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubeapps-service-catalog-browse
{{ template "kubeapps.user-rbac.labels" . }}
rules:
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - clusterservicebrokers
  - clusterserviceclasses
  - clusterserviceplans
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubeapps-service-catalog-read
{{ template "kubeapps.user-rbac.labels" . }}
rules:
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - serviceinstances
  - servicebindings
  verbs: 
  - list
  - get
  # Allows viewing Service Binding credentials.
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
# kubeapps-service-catalog-write
# Gives write access to Service Instances and Bindings within a Namespace in Kubeapps.
# Usage:
#   Apply kubeapps-service-catalog-write clusterrole to user/serviceaccount in the desired namespace.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubeapps-service-catalog-write
{{ template "kubeapps.user-rbac.labels" . }}
rules:
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - serviceinstances
  - servicebindings
  verbs:
  - create
  - delete
---
# kubeapps-service-catalog-admin
# Gives admin access for the Service Broker configuration page in Kubeapps.
# Usage:
#   Apply kubeapps-service-catalog-admin clusterrole to user/serviceaccount in all namespaces.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubeapps-service-catalog-admin
{{ template "kubeapps.user-rbac.labels" . }}
rules:
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - clusterservicebrokers
  verbs:
  - patch
---
# kubeapps-repositories-read
# Gives read-only access to App Repositories in Kubeapps.
# Usage:
#   Apply kubeapps-repositories-read role to user/serviceaccount in the kubeapps namespace.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: kubeapps-repositories-read
{{ template "kubeapps.user-rbac.labels" . }}
rules:
- apiGroups: 
  - kubeapps.com
  resources: 
  - apprepositories
  verbs: 
  - list
  - get
---
# kubeapps-repositories-write
# Gives write access to App Repositories in Kubeapps.
# Usage:
#   Apply kubeapps-repositories-write role to user/serviceaccount in the kubeapps namespace.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: kubeapps-repositories-write
{{ template "kubeapps.user-rbac.labels" . }}
rules:
- apiGroups: 
  - kubeapps.com
  resources: 
  - apprepositories
  verbs: 
  - get
  - create
  - update
  - delete
  # Allows creating secrets for storing repository credentials
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
{{- end -}}
