version: 2

## Build conditions
# Build in any branch or tag
build_always: &build_always
  filters:
    tags:
      only: /^v.*/
# Build only in master or in tags
build_on_master: &build_on_master
  filters:
    tags:
      only: /^v.*/
    branches:
      only: master
# Build only in tags (release)
build_on_tag: &build_on_tag
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

workflows:
  version: 2
  kubeapps:
    jobs:
      - test_go:
          <<: *build_always
      - test_dashboard:
          <<: *build_always
      - test_chart_render:
          <<: *build_always
      - build_go_images:
          <<: *build_always
      - build_dashboard:
          <<: *build_always
      - GKE_1_9:
          <<: *build_on_master
          requires:
            - test_go
            - test_dashboard
            - build_go_images
            - build_dashboard
      - GKE_1_10:
          <<: *build_on_master
          requires:
            - test_go
            - test_dashboard
            - build_go_images
            - build_dashboard
      - sync_chart:
          <<: *build_on_master
          requires:
            - GKE_1_9
            - GKE_1_10
      - push_images:
          <<: *build_always
          requires:
            - GKE_1_9
            - GKE_1_10
      - release:
          <<: *build_on_tag
          requires:
            - GKE_1_9
            - GKE_1_10

## Definitions
install_gcloud_sdk: &install_gcloud_sdk
  run: |
    echo "export PATH=$PATH:${HOME}/google-cloud-sdk/bin" >> $BASH_ENV
    echo "export CLOUDSDK_CORE_DISABLE_PROMPTS=1" >> $BASH_ENV
    if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash;
    fi
install_helm_cli: &install_helm_cli
  run: |
    wget https://storage.googleapis.com/kubernetes-helm/helm-$HELM_VERSION-linux-amd64.tar.gz
    tar zxf helm-$HELM_VERSION-linux-amd64.tar.gz
    sudo mv linux-amd64/helm /usr/local/bin/
exports: &exports
  run: |
    # It is not possible to resolve env vars in the environment section:
    # https://circleci.com/docs/2.0/env-vars/#using-bash_env-to-set-environment-variables
    # DEV_TAG and PROD_TAG are the tags used for the Kubeapps docker images
    echo "export DEV_TAG=build-${CIRCLE_SHA1}" >> $BASH_ENV
    echo "export PROD_TAG=${CIRCLE_TAG:-latest}" >> $BASH_ENV
    # Apart from using a DEV_TAG we use a different image ID to avoid polluting the tag
    # history of the production tag
    echo "export IMG_MODIFIER=-ci" >> $BASH_ENV
build_images: &build_images
  steps:
    - setup_remote_docker
    - checkout
    - <<: *exports
    - run: |
        read -ra IMG_ARRAY <<< "$IMAGES"
        for IMAGE in "${IMG_ARRAY[@]}"; do
          make IMG_MODIFIER="$IMG_MODIFIER" VERSION="${DEV_TAG}" ${IMAGE}
          if [[ -z "${CIRCLE_PULL_REQUEST}" && -n "${DOCKER_USERNAME}" && -n "${DOCKER_PASSWORD}" ]]; then
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker push ${IMAGE}${IMG_MODIFIER}:${DEV_TAG}
          fi
        done
gke_test: &gke_test
  docker:
    - image: circleci/golang:1.9
  steps:
    - run: |
        # In case of GKE we will only want to build if it is
        # a build of a branch in the kubeapps repository
        if [[ -z "$GKE_ADMIN" ]]; then
          circleci step halt
        fi
    - checkout
    - <<: *exports
    - <<: *install_gcloud_sdk
    # Install kubectl
    - run: gcloud components install kubectl
    - setup_remote_docker
    - run: |
        gcloud -q config set project $GKE_PROJECT
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/client_secrets.json
        echo $GCLOUD_KEY > $GOOGLE_APPLICATION_CREDENTIALS
        if [ -a $GOOGLE_APPLICATION_CREDENTIALS ]; then
          gcloud -q auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS;
        fi
    # A GKE cluster name cannot contain non-alphanumeric characters (nor uppercase letters)
    - run: echo "export ESCAPED_GKE_CLUSTER=$(echo ${GKE_CLUSTER}-${CIRCLE_BRANCH:-$CIRCLE_TAG}-${GKE_BRANCH}-ci | sed 's/[^a-z0-9-]//g')" >> $BASH_ENV
    - run: ./script/start-gke-env.sh $ESCAPED_GKE_CLUSTER $GKE_ZONE $GKE_BRANCH $GKE_ADMIN > /dev/null
    # Install helm
    - <<: *install_helm_cli
    - run: ./script/e2e-test.sh $DEV_TAG $IMG_MODIFIER
    - run:
        name: Cleanup GKE Cluster
        command: gcloud container clusters delete --async --zone $GKE_ZONE $ESCAPED_GKE_CLUSTER
        when: always
###

jobs:
  test_go:
    working_directory: /go/src/github.com/kubeapps/kubeapps
    environment:
      CGO_ENABLED: "0"
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - <<: *exports
      - run: make test
  test_dashboard:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install --cwd=dashboard --frozen-lockfile
      - run: yarn --cwd=dashboard run lint
      - run: yarn --cwd=dashboard run test --maxWorkers=4 --coverage
  test_chart_render:
    docker:
      - image: circleci/golang:1.9
    environment:
      HELM_VERSION: v2.9.1
    steps:
      - checkout
      - <<: *install_helm_cli
      - run: helm init --client-only
      - run: ./script/chart-template-test.sh
  build_go_images:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kubeapps/kubeapps
    environment:
      GOPATH: /home/circleci/.go_workspace
      IMAGES: "kubeapps/apprepository-controller kubeapps/chart-repo kubeapps/chartsvc kubeapps/tiller-proxy"
    <<: *build_images
  build_dashboard:
    docker:
      - image: circleci/golang:1.9
    environment:
      IMAGES: "kubeapps/dashboard"
    <<: *build_images
  release:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: REPO_DOMAIN=kubeapps REPO_NAME=kubeapps ./script/create_release.sh ${CIRCLE_TAG}
  GKE_1_9:
    <<: *gke_test
    environment:
      HELM_VERSION: v2.9.1
      GKE_BRANCH: 1.9
  GKE_1_10:
    <<: *gke_test
    environment:
      HELM_VERSION: v2.9.1
      GKE_BRANCH: 1.10
  sync_chart:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cc:ed:2d:1f:74:3b:32:c3:99:62:d7:7d:81:af:01:e0"
      - run: |
          if ls ~/.ssh/id_rsa_* 1> /dev/null 2>&1; then
            # Change order to use configured ssh_key first
            ssh-add -D
            ssh-add ~/.ssh/id_rsa_* ~/.ssh/id_rsa
          fi
          ./script/chart_sync.sh kubernetes-bitnami kubernetes@bitnami.com
  push_images:
    docker:
      - image: circleci/golang:1.9
    steps:
      - setup_remote_docker
      - <<: *exports
      - run: |
          if [[ -z "$CIRCLE_PULL_REQUEST" && -n "$DOCKER_USERNAME" && -n "$DOCKER_PASSWORD" ]]; then
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            for IMAGE in kubeapps/chart-repo kubeapps/chartsvc kubeapps/apprepository-controller kubeapps/dashboard kubeapps/tiller-proxy; do
              docker pull ${IMAGE}${IMG_MODIFIER}:${DEV_TAG}
              docker tag ${IMAGE}${IMG_MODIFIER}:${DEV_TAG} ${IMAGE}:${PROD_TAG}
              docker push ${IMAGE}:${PROD_TAG}
            done
          fi
