[package]
name = "pinniped-proxy"
version = "0.1.0"
authors = [
    "Andres Martinez <andresmgot@vmware.com>",
    "Antonio Gamez <agamez@vmware.com>",
    "Michael Nelson <minelson@vmware.com>"
    ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13"
hyper = "0.13"
hyper-tls = "0.4"
kube = { version = "0.43.0", features = ["derive"] }
kube-runtime = "0.43.0"
k8s-openapi = { version = "0.9.0", default-features = false, features = ["v1_17"] }
log = "0.4"
native-tls = "0.2"
openssl = "0.10"
pretty_env_logger = "0.4"
reqwest = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
thiserror = "1.0"
# Update to 0.3 once apparent issue with the nascent 0.3.5 is fixed.
tokio = { version = "0.2", features = ["full"] }
tokio-tls = "0.3"
url = "2.1"

[dev-dependencies]
tokio-test = "0.4"
serial_test = "0.5"
