[package]
name = "pinniped-proxy"
version = "0.1.0"
authors = [
    "Andres Martinez <andresmgot@vmware.com>",
    "Antonio Gamez <agamez@vmware.com>",
    "Michael Nelson <minelson@vmware.com>"
    ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
