apiVersion: {{ include "common.capabilities.crd.apiVersion" . }}
kind: CustomResourceDefinition
metadata:
  name: apprepositories.kubeapps.com
spec:
  group: kubeapps.com
  scope: Namespaced
  names:
    kind: AppRepository
    plural: apprepositories
    shortNames:
      - apprepos
  {{- if semverCompare "<1.19-0" (include "common.capabilities.kubeVersion" .) -}}
  version: v1alpha1
  {{- else }}
  versions:
    - name: v1alpha1
  {{- end }}
